var record;
record[Record.x] = ds_list_create();
record[Record.y] = ds_list_create();
record[Record.rm] = ds_list_create();
record[Record.sprite] = ds_list_create();
record[Record.subimg] = ds_list_create();
record[Record.xscale] = ds_list_create();
record[Record.yscale] = ds_list_create();
record[Record.state] = ds_list_create();
record[Record.target] = noone;
return record;